PORTNAME=	mcpelauncher
DISTVERSION=	1.4.1
CATEGORIES=	x11 games

MAINTAINER=	er2@dismail.de
COMMENT=	Minecraft Bedrock Edition launcher
WWW=		https://mcpelauncher.readthedocs.io/

RUN_DEPENDS=	mcpelauncher-core>0:games/mcpelauncher-core \
		mcpelauncher-msa>0:games/mcpelauncher-msa \
		mcpelauncher-ui>0:games/mcpelauncher-ui

USES=		metaport qt:6
USE_QT=		# empty

.include <bsd.port.mk>
