PORTNAME=	jsdec
PORTVERSION=	0.7.0
DISTVERSIONPREFIX=v
PORTREVISION=	1
CATEGORIES=	lang devel
PKGNAMEPREFIX=	rizin-

MAINTAINER=	er2@dismail.de
COMMENT=	Simple decompiler for Rizin
WWW=		https://github.com/rizinorg/jsdec

LICENSE=	BSD3CLAUSE MIT
LICENSE_COMB=	dual

LIB_DEPENDS=	libquickjs.so:lang/quickjs

USES=		compiler:c++11-lib pkgconfig meson
USE_GITHUB=	yes
GH_ACCOUNT=	rizinorg

.include <bsd.port.mk>
